### ISSUE TITLE
Error in lecture 10 "Numerical methods"

### ISSUE THREAD

**Issue by shulgin-egor** [MerkulovDaniil/mipt_optimization#1]
![2018-02-14 13 17 21](https://user-images.githubusercontent.com/14257816/36199050-70bbe140-1189-11e8-9189-80a6b38b249a.png)
In second case "||x_{k+1} - x^* || <= C ||x_k - x^*||" C must be in (0,1), or there should be 'q'.

**Comment by MerkulovDaniil** [comment]
Sure! Thx
